export const CURRENT_LOCATION = "CURRENT_LOCATION";
export const AUTOCOMPLETE = "AUTOCOMPLETE";
export const CURRENT_WEATHER = "CURRENT_WEATHER";
export const GET_FAVORITES = "GET_FAVORITES";
export const FIVE_DAY_FORECAST = "FIVE_DAY_FORECAST";
export const RESET = "RESET";
